// src/test/coverage.test.ts
//
// THE GUARD. Scans the live Robotku toolbox for every block type and cross-checks
// it against the block types referenced by the parity suites (src/test/*.test.ts).
// It writes src/test/COVERAGE.md and FAILS if any toolbox block has no test, so an
// untested block is impossible to ship unnoticed.
//
// Reporters/statements are "referenced" by appearing as `type: '<block>'` in a
// test spec — the same specs the harness feeds through the real generator — so a
// green row here means the block genuinely round-tripped block → command → sim.

import { describe, it, expect } from 'vitest';
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { ensureInit } from './harness';
import { getAstroidToolbox } from '../toolbox';

const TEST_DIR = dirname(fileURLToPath(import.meta.url));

// --- Dynamic (flyout) blocks the toolbox exposes without a static `kind:block`.
// Variables/Functions use Blockly's VARIABLE/PROCEDURE flyouts; Parts (mechanisms)
// are streamed by the mechanisms category. The matrix still requires each tested.
const DYNAMIC_GROUPS: Array<{ name: string; blocks: string[] }> = [
  { name: 'Variables', blocks: ['variables_set', 'variables_get'] },
  {
    name: 'Functions',
    blocks: ['procedures_defnoreturn', 'procedures_callnoreturn', 'procedures_ifreturn'],
  },
  { name: 'Templates', blocks: ['templates_comment'] }, // custom flyout (gallery is the primary UI)
  { name: 'Parts', blocks: ['mechanism_set_head', 'mechanism_set_gripper'] },
];

// Not a user program block: the immovable hat.
const NON_PROGRAM = new Set(['program_start']);

function collectBlocks(node: any, out: string[]): void {
  if (!node) return;
  if (Array.isArray(node)) return node.forEach((n) => collectBlocks(n, out));
  if (node.kind === 'block' && node.type) out.push(node.type);
  if (node.contents) collectBlocks(node.contents, out);
}

/** Toolbox categories → { name, blocks[] }, with dynamic flyout groups injected. */
function toolboxGroups(): Array<{ name: string; blocks: string[] }> {
  const toolbox = getAstroidToolbox() as any;
  const groups: Array<{ name: string; blocks: string[] }> = [];
  for (const cat of toolbox.contents) {
    if (cat?.kind !== 'category') continue;
    const dynamic = DYNAMIC_GROUPS.find((g) => g.name === cat.name);
    if (dynamic) {
      groups.push({ name: cat.name, blocks: [...dynamic.blocks] });
      continue;
    }
    const blocks: string[] = [];
    collectBlocks(cat.contents, blocks);
    groups.push({ name: cat.name, blocks: blocks.filter((b) => !NON_PROGRAM.has(b)) });
  }
  // Parts (mechanisms) is streamed but not a top-level toolbox category.
  if (!groups.some((g) => g.name === 'Parts')) {
    groups.push(DYNAMIC_GROUPS.find((g) => g.name === 'Parts')!);
  }
  return groups;
}

/** Every block type referenced as `type: '<x>'` across the parity suites. */
function testedBlocks(): Set<string> {
  const tested = new Set<string>();
  const re = /type:\s*['"]([a-zA-Z0-9_]+)['"]/g;
  for (const file of readdirSync(TEST_DIR)) {
    if (!file.endsWith('.test.ts') || file === 'coverage.test.ts') continue;
    const src = readFileSync(join(TEST_DIR, file), 'utf8');
    for (const m of src.matchAll(re)) tested.add(m[1]);
  }
  return tested;
}

describe('Coverage guard: every toolbox block has a parity test', () => {
  ensureInit();
  const groups = toolboxGroups();
  const tested = testedBlocks();

  // AI blocks are implemented (PROMPT E) and tested like everything else now.
  const required = groups.flatMap((g) => g.blocks);
  const missing = [...new Set(required)].filter((b) => !tested.has(b)).sort();

  // --- Emit the human-readable report --------------------------------------
  const status = (b: string) => (tested.has(b) ? '✅ tested' : '❌ MISSING');
  const lines: string[] = [
    '# Robotku Block Coverage',
    '',
    '_Auto-generated by `src/test/coverage.test.ts` on every `npm test` run._',
    '_A block is "tested" when it appears as `type: \'<block>\'` in a parity spec — i.e. it was',
    'built into a real workspace and run through the shared generator + simulator._',
    '',
    `**${[...new Set(required)].filter((b) => tested.has(b)).length} / ${new Set(required).size}** program blocks covered.`,
    '',
  ];
  for (const g of groups) {
    const uniq = [...new Set(g.blocks)];
    if (uniq.length === 0) continue;
    lines.push(`## ${g.name}`, '');
    lines.push('| Block | Status |', '| --- | --- |');
    for (const b of uniq) {
      lines.push(`| \`${b}\` | ${status(b)} |`);
    }
    lines.push('');
  }
  writeFileSync(join(TEST_DIR, 'COVERAGE.md'), lines.join('\n'), 'utf8');

  it('reports zero untested toolbox blocks', () => {
    expect(missing, `Untested toolbox blocks: ${missing.join(', ')}`).toEqual([]);
  });

  it('every tested block still exists in the toolbox (no stale tests)', () => {
    const known = new Set([...groups.flatMap((g) => g.blocks)]);
    // Standard Blockly primitives used purely as literals/among helpers are allowed.
    const allowedExtras = new Set(['math_number', 'text', 'logic_boolean', 'program_start']);
    const stale = [...tested].filter(
      (b) =>
        !known.has(b) &&
        !allowedExtras.has(b) &&
        !b.startsWith('controls_') &&
        !b.startsWith('logic_') &&
        !b.startsWith('math_') &&
        !b.startsWith('ai_'), // AI blocks incl. the deprecated ai_object_detected alias
    );
    expect(stale, `Tests reference unknown blocks: ${stale.join(', ')}`).toEqual([]);
  });
});
