// P3 — reconciliation safety net: every opcode a block can stream to the board must
// be EITHER handled by the firmware, OR correctly marked unsupported by the
// BoardProfile (toolbox greys it + firmware answers UNSUPPORTED — the two agree),
// OR a documented firmware-TODO (hardware exists, handler not landed yet). A NEW
// "dangling" opcode — profile says runnable, firmware has no handler, not a known
// TODO — fails this test. Also emits docs/opcode-status.md as the Protokol Robotku
// v1 appendix.
import { describe, it, expect } from 'vitest';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { BLOCK_OPCODE } from '../blockcoding/blockOpcodes';
import { isSupported, HOST_ONLY, robotkuEsp32V3 } from '../domain/boardProfile';

// Device opcodes the firmware implements, read straight from main.cpp so a firmware
// change is reflected here without editing this test.
function firmwareHandlers(): Set<string> {
  const src = readFileSync(
    resolve(process.cwd(), 'firmware/robotku-esp32/src/main.cpp'),
    'utf8',
  );
  const out = new Set<string>();
  for (const m of src.matchAll(/strcmp\(cmd,\s*"([A-Z_]+)"\)/g)) out.add(m[1]);
  return out;
}

// Profile-supported opcodes whose firmware handler hasn't landed yet. Each is a real
// hardware capability (see boardProfile TODO / pin.md FW-06) that currently answers
// UNSUPPORTED. Shrinks as firmware catches up; a new entry here is a conscious IOU.
const FW_TODO = new Set<string>([
  'STOP', // move_stop — trivial (= stopAllActuators), not yet wired
  'STEER_TIMED', // move_steer — differential steer on tank drive, not yet wired
  'SET_LED_COLOR', // RGB LED GPIO16/17/5 (FW-06)
  'SET_LED_BRIGHTNESS', // RGB brightness (FW-06)
  'DISPLAY_TEXT', // OLED text
]);

type Status = 'handled' | 'unsupported-by-profile' | 'fw-todo' | 'DANGLING';

function classify(opcode: string, handlers: Set<string>): Status {
  if (handlers.has(opcode)) return 'handled';
  if (!isSupported(opcode, robotkuEsp32V3)) return 'unsupported-by-profile';
  return FW_TODO.has(opcode) ? 'fw-todo' : 'DANGLING';
}

describe('opcode reconciliation (P3)', () => {
  const handlers = firmwareHandlers();
  const deviceOpcodes = [...new Set(Object.values(BLOCK_OPCODE))].sort();

  it('has no dangling opcode (block emits it, board neither handles nor is it a known gap)', () => {
    const dangling = deviceOpcodes.filter((op) => classify(op, handlers) === 'DANGLING');
    expect(dangling, `dangling opcodes: ${dangling.join(', ')}`).toEqual([]);
  });

  it('FW_TODO stays honest — no stale entry that is actually handled or unsupported', () => {
    for (const op of FW_TODO) {
      expect(handlers.has(op), `${op} now has a firmware handler — drop it from FW_TODO`).toBe(
        false,
      );
      expect(isSupported(op, robotkuEsp32V3), `${op} is not profile-supported — remove from FW_TODO`).toBe(
        true,
      );
    }
  });

  it('writes docs/opcode-status.md', () => {
    const rows = deviceOpcodes.map((op) => {
      const blocks = Object.entries(BLOCK_OPCODE)
        .filter(([, o]) => o === op)
        .map(([b]) => b)
        .join(', ');
      return `| \`${op}\` | ${classify(op, handlers)} | ${blocks} |`;
    });
    const hostRows = [...HOST_ONLY]
      .sort()
      .map((op) => `| \`${op}\` | host-only | — |`);

    const md = `# Robotku Protocol v1 — Opcode ↔ Handler Status

> Generated by \`src/test/opcodeReconciliation.test.ts\`. Do not edit by hand.
> Board profile: \`${robotkuEsp32V3.id}\`. Firmware handlers read from
> \`firmware/robotku-esp32/src/main.cpp\`.

**Status legend**
- \`handled\` — firmware has a handler; profile supports it. Runs on the board.
- \`unsupported-by-profile\` — no hardware; toolbox greys the block, firmware replies UNSUPPORTED.
- \`fw-todo\` — hardware exists, firmware handler not landed yet (answers UNSUPPORTED meanwhile).
- \`host-only\` — interpreted on the host, never streamed to the board.

## Device opcodes (block-emittable)

| Opcode | Status | Blocks |
|---|---|---|
${rows.join('\n')}

## Host-only opcodes

| Opcode | Status | Blocks |
|---|---|---|
${hostRows.join('\n')}
`;
    mkdirSync(resolve(process.cwd(), 'docs'), { recursive: true });
    writeFileSync(resolve(process.cwd(), 'docs/opcode-status.md'), md);
    expect(md).toContain('handled');
  });
});
