import type { DocEntry } from './types';

const LABEL = { name: 'label', type: 'teks', default: '"any"', desc: 'Nama objek, mis. "cat".' };

export const AI_DOCS: DocEntry[] = [
  {
    slug: 'ai/use-model',
    title: 'ai.use_model',
    category: 'AI',
    summary: 'Memilih model AI yang dipakai kamera.',
    description: 'Menyetel model pengenalan objek yang akan dipakai oleh kamera.',
    signature: { python: 'ai.use_model("<id_model>")', opcode: 'AI_SET_MODEL' },
    params: [{ name: 'model', type: 'teks', desc: 'ID model yang dipakai.' }],
    blockPreview: { blockType: 'ai_use_model' },
    seeAlso: ['ai/camera', 'ai/detected'],
  },
  {
    slug: 'ai/camera',
    title: 'camera.on / camera.off',
    category: 'AI',
    summary: 'Menyalakan atau mematikan kamera AI.',
    description: 'Menghidupkan kamera untuk mulai mendeteksi objek, atau mematikannya.',
    signature: { python: 'camera.on()', opcode: 'AI_CAMERA' },
    blockPreview: { blockType: 'ai_camera_on', fields: { STATE: 'on' } },
    examples: [{ title: 'Nyalakan kamera', python: 'camera.on()', runnable: false }],
    seeAlso: ['ai/use-model', 'ai/detected'],
  },
  {
    slug: 'ai/detected',
    title: 'ai.detected',
    category: 'AI',
    summary: 'Benar bila objek terlihat kamera.',
    description: 'Bernilai True saat kamera melihat objek dengan label yang diberikan.',
    signature: { python: 'ai.detected("cat")', opcode: 'GET_AI_DATA' },
    params: [LABEL],
    returns: { type: 'boolean', desc: 'True jika terdeteksi.' },
    blockPreview: { blockType: 'ai_detected', fields: { LABEL: 'any' } },
    examples: [
      {
        title: 'Reaksi lihat kucing',
        python: 'if ai.detected("cat"):\n    display.text("kucing!")',
        runnable: false,
      },
    ],
    seeAlso: ['ai/confidence', 'ai/object-count', 'ai/wait-until-seen'],
  },
  {
    slug: 'ai/confidence',
    title: 'ai.confidence',
    category: 'AI',
    summary: 'Tingkat keyakinan deteksi (0–100).',
    description: 'Mengembalikan seberapa yakin kamera terhadap objek yang dikenali.',
    signature: { python: 'ai.confidence("cat")', opcode: 'GET_AI_DATA' },
    params: [LABEL],
    returns: { type: 'angka', desc: '0 … 100.' },
    blockPreview: { blockType: 'ai_confidence', fields: { LABEL: 'any' } },
    seeAlso: ['ai/detected'],
  },
  {
    slug: 'ai/object-count',
    title: 'ai.object_count',
    category: 'AI',
    summary: 'Jumlah objek yang terlihat.',
    description: 'Mengembalikan berapa banyak objek berlabel tertentu yang dilihat kamera.',
    signature: { python: 'ai.object_count("cat")', opcode: 'GET_AI_DATA' },
    params: [LABEL],
    returns: { type: 'angka', desc: 'Jumlah objek.' },
    blockPreview: { blockType: 'ai_object_count', fields: { LABEL: 'any' } },
    seeAlso: ['ai/detected'],
  },
  {
    slug: 'ai/bbox',
    title: 'ai.bbox',
    category: 'AI',
    summary: 'Posisi/ukuran kotak objek.',
    description: 'Mengembalikan bagian kotak deteksi: x, y, lebar (w), atau tinggi (h), skala 0–100.',
    signature: { python: 'ai.bbox("cat", "x")', opcode: 'GET_AI_DATA' },
    params: [LABEL, { name: 'part', type: 'teks', desc: '"x", "y", "w", atau "h".' }],
    returns: { type: 'angka', desc: '0 … 100 dari frame.' },
    blockPreview: { blockType: 'ai_bbox', fields: { LABEL: 'any', PART: 'x' } },
    seeAlso: ['ai/detected'],
  },
  {
    slug: 'ai/wait-until-seen',
    title: 'ai.wait_until_seen',
    category: 'AI',
    summary: 'Tunggu sampai objek terlihat.',
    description: 'Menjeda program sampai kamera melihat objek berlabel tertentu.',
    signature: { python: 'ai.wait_until_seen("cat")', opcode: 'WAIT_UNTIL' },
    params: [LABEL],
    blockPreview: { blockType: 'ai_wait_until_seen', fields: { LABEL: 'any' } },
    seeAlso: ['ai/detected', 'timing/wait-until'],
  },
];
