import type { DocEntry } from './types';

const WAIT = { name: 'wait', type: 'teks', default: '"true"', desc: 'Tunggu selesai sebelum lanjut.' };

export const AUDIO_DOCS: DocEntry[] = [
  {
    slug: 'audio/record',
    title: 'audio.record',
    category: 'Audio',
    summary: 'Merekam suara ke slot memori.',
    description: 'Merekam audio selama beberapa detik dan menyimpannya ke slot yang dipilih.',
    signature: { python: 'audio.record(slot=1, sec=detik, wait="true")', opcode: 'RECORD_AUDIO' },
    params: [
      { name: 'slot', type: 'angka', default: '1', desc: 'Nomor slot memori.' },
      { name: 'sec', type: 'angka', default: '1', desc: 'Lama rekam.' },
      WAIT,
    ],
    blockPreview: { blockType: 'audio_record' },
    seeAlso: ['audio/play-recording', 'sensors/is-recording'],
  },
  {
    slug: 'audio/play-recording',
    title: 'audio.play_recording',
    category: 'Audio',
    summary: 'Memutar rekaman dari slot.',
    description: 'Memutar suara yang tersimpan di slot memori.',
    signature: { python: 'audio.play_recording(slot=1, wait="true")', opcode: 'PLAY_RECORDING' },
    params: [{ name: 'slot', type: 'angka', default: '1', desc: 'Slot yang diputar.' }, WAIT],
    blockPreview: { blockType: 'audio_play_recording' },
    seeAlso: ['audio/record'],
  },
  {
    slug: 'audio/sound-effect',
    title: 'audio.sound_effect',
    category: 'Audio',
    summary: 'Memainkan efek suara siap pakai.',
    description: 'Memutar efek suara bawaan (mis. "short_beep").',
    signature: { python: 'audio.sound_effect("short_beep", wait="true")', opcode: 'PLAY_SOUND_EFFECT' },
    params: [{ name: 'efek', type: 'teks', desc: 'Nama efek suara.' }, WAIT],
    blockPreview: { blockType: 'audio_sound_effect' },
    seeAlso: ['audio/tone', 'audio/melody'],
  },
  {
    slug: 'audio/tone',
    title: 'audio.tone',
    category: 'Audio',
    summary: 'Memainkan satu nada beberapa detik.',
    description: 'Membunyikan nada (mis. "C4") selama waktu tertentu.',
    signature: { python: 'audio.tone("C4", detik, wait="true")', opcode: 'PLAY_TONE' },
    params: [
      { name: 'nada', type: 'teks', default: '"C4"', desc: 'Nama nada, mis. "C4", "E4".' },
      { name: 'detik', type: 'angka', default: '1', desc: 'Durasi.' },
      WAIT,
    ],
    blockPreview: { blockType: 'audio_play_tone_sec', fields: { NOTE: 'C4' } },
    examples: [{ title: 'Bunyi C4', python: 'audio.tone("C4", 0.5)', runnable: true }],
    seeAlso: ['audio/tone-beat', 'audio/melody', 'audio/volume'],
  },
  {
    slug: 'audio/tone-beat',
    title: 'audio.tone_beat',
    category: 'Audio',
    summary: 'Memainkan nada sepanjang beberapa ketuk.',
    description: 'Seperti audio.tone tetapi durasinya dihitung dalam ketukan (beat) sesuai BPM.',
    signature: { python: 'audio.tone_beat("C4", ketuk, wait="true")', opcode: 'PLAY_TONE' },
    params: [
      { name: 'nada', type: 'teks', default: '"C4"', desc: 'Nama nada.' },
      { name: 'ketuk', type: 'angka', default: '1', desc: 'Jumlah ketukan.' },
      WAIT,
    ],
    blockPreview: { blockType: 'audio_play_tone_beat', fields: { NOTE: 'C4' } },
    seeAlso: ['audio/tone', 'audio/bpm'],
  },
  {
    slug: 'audio/melody',
    title: 'audio.melody',
    category: 'Audio',
    summary: 'Memainkan lagu siap pakai.',
    description: 'Memutar melodi bawaan (mis. "twinkle").',
    signature: { python: 'audio.melody("twinkle")', opcode: 'PLAY_TONE' },
    params: [{ name: 'lagu', type: 'teks', desc: 'Nama lagu.' }],
    blockPreview: { blockType: 'audio_play_melody' },
    seeAlso: ['audio/tone'],
    notes: ['Satu baris ini menjadi banyak perintah nada (satu per not).'],
  },
  {
    slug: 'audio/volume',
    title: 'audio.volume',
    category: 'Audio',
    summary: 'Mengatur volume suara.',
    description: 'Menyetel volume dari 0 (senyap) sampai 100 (maksimal).',
    signature: { python: 'audio.volume(nilai)', opcode: 'SET_VOLUME' },
    params: [{ name: 'nilai', type: 'angka', default: '80', desc: 'Volume.', range: '0 … 100' }],
    blockPreview: { blockType: 'audio_set_volume', fields: { VALUE: 80 } },
    seeAlso: ['audio/tone', 'audio/stop'],
  },
  {
    slug: 'audio/stop',
    title: 'audio.stop',
    category: 'Audio',
    summary: 'Menghentikan semua suara.',
    description: 'Mematikan semua bunyi yang sedang dimainkan.',
    signature: { python: 'audio.stop()', opcode: 'STOP_SOUNDS' },
    blockPreview: { blockType: 'audio_stop_sounds' },
    seeAlso: ['audio/tone'],
  },
  {
    slug: 'audio/bpm',
    title: 'audio.bpm',
    category: 'Audio',
    summary: 'Mengatur tempo (ketukan per menit).',
    description: 'Menyetel kecepatan lagu/ketukan yang dipakai oleh audio.tone_beat.',
    signature: { python: 'audio.bpm(nilai)', opcode: 'SET_BPM' },
    params: [{ name: 'nilai', type: 'angka', default: '120', desc: 'Ketukan per menit.' }],
    blockPreview: { blockType: 'audio_set_bpm', fields: { BPM: 120 } },
    seeAlso: ['audio/tone-beat'],
  },
];
