import type { DocEntry } from './types';

const SEC = { name: 'detik', type: 'angka', default: '1', desc: 'Lama tampil dalam detik.' };

export const DISPLAY_DOCS: DocEntry[] = [
  {
    slug: 'display/matrix',
    title: 'display.matrix',
    category: 'Display',
    summary: 'Menampilkan pola LED 5×5.',
    description: 'Menyalakan pola lampu dari 25 karakter 0/1 (baris demi baris) selama beberapa detik.',
    signature: { python: 'display.matrix(pola, detik)', opcode: 'DISPLAY_MATRIX' },
    params: [
      { name: 'pola', type: 'teks', desc: '25 karakter 0/1 (1 = nyala).' },
      SEC,
    ],
    blockPreview: { blockType: 'display_matrix' },
    seeAlso: ['display/clear', 'display/text'],
  },
  {
    slug: 'display/text',
    title: 'display.text',
    category: 'Display',
    summary: 'Menampilkan teks di layar.',
    description: 'Menulis kalimat di layar OLED. Teks panjang akan bergeser (scroll).',
    signature: { python: 'display.text("teks")', opcode: 'DISPLAY_TEXT' },
    params: [{ name: 'teks', type: 'teks', desc: 'Kalimat yang ditampilkan.' }],
    blockPreview: { blockType: 'display_text', fields: { TEXT: 'Hi!' } },
    examples: [
      {
        title: 'Sapa',
        python: 'display.text("Halo!")',
        blocks: [{ type: 'display_text', fields: { TEXT: 'Halo!' } }],
        runnable: true,
      },
    ],
    seeAlso: ['display/face', 'display/clear'],
    notes: ['Butuh modul layar OLED.'],
  },
  {
    slug: 'display/face',
    title: 'display.face',
    category: 'Display',
    summary: 'Menampilkan wajah kaomoji.',
    description: 'Menampilkan emotikon teks (kaomoji) seperti (^_^) di layar.',
    signature: { python: 'display.face("(^_^)")', opcode: 'DISPLAY_TEXT' },
    params: [{ name: 'wajah', type: 'teks', desc: 'Kaomoji, mis. "(^_^)".' }],
    blockPreview: { blockType: 'display_kaomoji', fields: { FACE: '(^_^)' } },
    examples: [
      {
        title: 'Senyum',
        python: 'display.face("(^_^)")',
        blocks: [{ type: 'display_kaomoji', fields: { FACE: '(^_^)' } }],
        runnable: true,
      },
    ],
    seeAlso: ['display/text'],
    notes: ['Butuh modul layar OLED.'],
  },
  {
    slug: 'display/brightness',
    title: 'display.brightness',
    category: 'Display',
    summary: 'Mengatur kecerahan layar.',
    description: 'Menyetel tingkat kecerahan layar dari 0 (redup) sampai 100 (terang).',
    signature: { python: 'display.brightness(nilai)', opcode: 'SET_LED_BRIGHTNESS' },
    params: [{ name: 'nilai', type: 'angka', default: '100', desc: 'Kecerahan.', range: '0 … 100' }],
    blockPreview: { blockType: 'display_set_brightness', fields: { VALUE: 100 } },
    seeAlso: ['display/text'],
  },
  {
    slug: 'display/clear',
    title: 'display.clear',
    category: 'Display',
    summary: 'Mengosongkan layar.',
    description: 'Menghapus semua yang tampil di layar.',
    signature: { python: 'display.clear()', opcode: 'CLEAR_MATRIX' },
    blockPreview: { blockType: 'display_clear_matrix' },
    seeAlso: ['display/text', 'display/matrix'],
  },
  {
    slug: 'display/led-color',
    title: 'led.color',
    category: 'Display',
    summary: 'Menyalakan LED warna.',
    description: 'Menyalakan LED RGB dengan warna (kode hex) selama beberapa detik.',
    signature: { python: 'led.color("#ff0000", detik)', opcode: 'SET_LED_COLOR' },
    params: [
      { name: 'warna', type: 'teks', default: '"#ff0000"', desc: 'Kode warna hex.' },
      SEC,
    ],
    blockPreview: { blockType: 'set_led_color', fields: { COLOR: '#ff0000' } },
    examples: [
      {
        title: 'Nyala hijau',
        python: 'led.color("#00ff00", 2)',
        blocks: [{ type: 'set_led_color', fields: { COLOR: '#00ff00' }, inputs: { DURATION: 2 } }],
        runnable: true,
      },
    ],
    seeAlso: ['display/brightness'],
  },
  {
    slug: 'display/lcd-shape',
    title: 'lcd.shape',
    category: 'Display',
    summary: 'Menampilkan bentuk di layar LCD.',
    description: 'Menggambar bentuk (mis. hati, bintang) di layar selama beberapa detik.',
    signature: { python: 'lcd.shape("heart", detik)', opcode: 'LCD_SHAPE' },
    params: [
      { name: 'bentuk', type: 'teks', desc: 'Nama bentuk, mis. "heart", "star".' },
      SEC,
    ],
    blockPreview: { blockType: 'lcd_shape' },
    seeAlso: ['display/lcd-text', 'display/lcd-clear'],
  },
  {
    slug: 'display/lcd-text',
    title: 'lcd.text',
    category: 'Display',
    summary: 'Menampilkan teks di layar LCD.',
    description: 'Menulis teks di layar LCD selama beberapa detik.',
    signature: { python: 'lcd.text("Hi", detik)', opcode: 'LCD_TEXT' },
    params: [{ name: 'teks', type: 'teks', desc: 'Teks yang ditampilkan.' }, SEC],
    blockPreview: { blockType: 'lcd_text', fields: { TEXT: 'Hi' } },
    seeAlso: ['display/lcd-shape', 'display/lcd-clear'],
  },
  {
    slug: 'display/lcd-clear',
    title: 'lcd.clear',
    category: 'Display',
    summary: 'Mengosongkan layar LCD.',
    description: 'Menghapus isi layar LCD.',
    signature: { python: 'lcd.clear()', opcode: 'LCD_CLEAR' },
    blockPreview: { blockType: 'lcd_clear' },
    seeAlso: ['display/lcd-text'],
  },
];
