import type { DocEntry } from './types';

const PORT = { name: 'port', type: 'teks', default: '"G1"', desc: 'Port sensor, G1–G8.' };
const num = (type = 'angka') => ({ type, desc: 'Nilai yang dibaca.' });

export const SENSORS_DOCS: DocEntry[] = [
  {
    slug: 'sensors/button',
    title: 'sensors.button1 / button2',
    category: 'Sensors & Data',
    summary: 'Benar saat tombol ditekan.',
    description: 'Membaca tombol bawaan. Bernilai True saat ditekan, False saat tidak.',
    signature: { python: 'sensors.button1()', opcode: 'GET_SENSOR_DATA' },
    returns: { type: 'boolean', desc: 'True jika tombol ditekan.' },
    blockPreview: { blockType: 'sensor_button1' },
    examples: [
      {
        title: 'Aksi saat ditekan',
        python: 'if sensors.button1():\n    display.text("A!")',
        runnable: false,
      },
    ],
    seeAlso: ['timing/wait-until'],
  },
  {
    slug: 'sensors/is-recording',
    title: 'sensors.is_recording',
    category: 'Sensors & Data',
    summary: 'Benar saat sedang merekam audio.',
    description: 'Bernilai True selama proses rekam audio berlangsung.',
    signature: { python: 'sensors.is_recording()', opcode: 'GET_SENSOR_DATA' },
    returns: { type: 'boolean', desc: 'Status rekam.' },
    blockPreview: { blockType: 'sensor_is_recording' },
    seeAlso: ['audio/record'],
  },
  {
    slug: 'sensors/analog',
    title: 'sensors.analog',
    category: 'Sensors & Data',
    summary: 'Membaca nilai analog sebuah port.',
    description: 'Mengembalikan angka 0–1023 dari pin analog.',
    signature: { python: 'sensors.analog(port)', opcode: 'GET_SENSOR_DATA' },
    params: [{ ...PORT }],
    returns: { type: 'angka', desc: '0 … 1023.' },
    blockPreview: { blockType: 'sensor_get_analog', fields: { PORT: 'G1' } },
    seeAlso: ['sensors/digital', 'sensors/set-analog'],
  },
  {
    slug: 'sensors/digital',
    title: 'sensors.digital',
    category: 'Sensors & Data',
    summary: 'Membaca nilai digital sebuah port.',
    description: 'Mengembalikan 0 atau 1 dari pin digital.',
    signature: { python: 'sensors.digital(port)', opcode: 'GET_SENSOR_DATA' },
    params: [{ ...PORT }],
    returns: { type: 'angka', desc: '0 atau 1.' },
    blockPreview: { blockType: 'sensor_get_digital', fields: { PORT: 'G1' } },
    seeAlso: ['sensors/analog', 'sensors/set-digital'],
  },
  {
    slug: 'sensors/ultrasonic',
    title: 'sensors.ultrasonic',
    category: 'Sensors & Data',
    summary: 'Membaca jarak dengan sensor ultrasonik.',
    description: 'Mengukur jarak ke objek di depan sensor dalam cm atau inch.',
    signature: { python: 'sensors.ultrasonic(port="G1", unit="cm")', opcode: 'GET_SENSOR_DATA' },
    params: [{ ...PORT }, { name: 'unit', type: 'teks', default: '"cm"', desc: '"cm" atau "inch".' }],
    returns: { type: 'angka', desc: 'Jarak.' },
    blockPreview: { blockType: 'sensor_ultrasonic', fields: { PORT: 'G1', UNIT: 'cm' } },
    examples: [
      {
        title: 'Berhenti kalau dekat',
        python: 'if sensors.ultrasonic(port="G1") < 10:\n    robot.stop_all()',
        runnable: false,
      },
    ],
    seeAlso: ['sensors/distance', 'flow/while'],
  },
  {
    slug: 'sensors/temperature',
    title: 'sensors.temperature',
    category: 'Sensors & Data',
    summary: 'Membaca suhu.',
    description: 'Mengembalikan suhu yang terbaca sensor (°C).',
    signature: { python: 'sensors.temperature(port="G1")', opcode: 'GET_SENSOR_DATA' },
    params: [{ ...PORT }],
    returns: num(),
    blockPreview: { blockType: 'sensor_temperature', fields: { PORT: 'G1' } },
    seeAlso: ['sensors/humidity'],
  },
  {
    slug: 'sensors/humidity',
    title: 'sensors.humidity',
    category: 'Sensors & Data',
    summary: 'Membaca kelembapan.',
    description: 'Mengembalikan kelembapan udara (%).',
    signature: { python: 'sensors.humidity(port="G1")', opcode: 'GET_SENSOR_DATA' },
    params: [{ ...PORT }],
    returns: num(),
    blockPreview: { blockType: 'sensor_humidity', fields: { PORT: 'G1' } },
    seeAlso: ['sensors/temperature'],
  },
  {
    slug: 'sensors/light',
    title: 'sensors.light',
    category: 'Sensors & Data',
    summary: 'Membaca intensitas cahaya.',
    description: 'Mengembalikan tingkat cahaya yang terbaca sensor.',
    signature: { python: 'sensors.light(port="G1")', opcode: 'GET_SENSOR_DATA' },
    params: [{ ...PORT }],
    returns: num(),
    blockPreview: { blockType: 'sensor_light', fields: { PORT: 'G1' } },
    seeAlso: ['sensors/analog'],
  },
  {
    slug: 'sensors/distance',
    title: 'sensors.distance',
    category: 'Sensors & Data',
    summary: 'Membaca jarak tempuh.',
    description: 'Mengembalikan jarak yang sudah ditempuh robot sejak terakhir di-reset.',
    signature: { python: 'sensors.distance(port="G1")', opcode: 'GET_SENSOR_DATA' },
    params: [{ ...PORT }],
    returns: num(),
    blockPreview: { blockType: 'sensor_distance', fields: { PORT: 'G1' } },
    seeAlso: ['sensors/reset-distance'],
  },
  {
    slug: 'sensors/heading',
    title: 'sensors.heading',
    category: 'Sensors & Data',
    summary: 'Membaca arah hadap (derajat).',
    description: 'Mengembalikan sudut arah hadap robot dalam derajat.',
    signature: { python: 'sensors.heading(port="G1")', opcode: 'GET_SENSOR_DATA' },
    params: [{ ...PORT }],
    returns: num(),
    blockPreview: { blockType: 'sensor_heading', fields: { PORT: 'G1' } },
    seeAlso: ['sensors/reset-heading'],
  },
  {
    slug: 'sensors/set-analog',
    title: 'sensors.set_analog',
    category: 'Sensors & Data',
    summary: 'Menulis nilai analog ke port.',
    description: 'Menyetel keluaran analog (0–255) pada sebuah pin.',
    signature: { python: 'sensors.set_analog(port, nilai)', opcode: 'SET_ANALOG' },
    params: [{ ...PORT }, { name: 'nilai', type: 'angka', desc: 'Nilai analog.', range: '0 … 255' }],
    blockPreview: { blockType: 'sensor_set_analog', fields: { PORT: 'G1' } },
    seeAlso: ['sensors/analog'],
  },
  {
    slug: 'sensors/set-digital',
    title: 'sensors.set_digital',
    category: 'Sensors & Data',
    summary: 'Menulis HIGH/LOW ke port.',
    description: 'Menyetel pin digital ke "HIGH" atau "LOW".',
    signature: { python: 'sensors.set_digital(port, "HIGH")', opcode: 'SET_DIGITAL' },
    params: [{ ...PORT }, { name: 'nilai', type: 'teks', desc: '"HIGH" atau "LOW".' }],
    blockPreview: { blockType: 'sensor_set_digital', fields: { PORT: 'G1' } },
    seeAlso: ['sensors/digital'],
  },
  {
    slug: 'sensors/reset-distance',
    title: 'sensors.reset_distance',
    category: 'Sensors & Data',
    summary: 'Mengembalikan hitungan jarak ke nol.',
    description: 'Menyetel ulang penghitung jarak tempuh ke 0.',
    signature: { python: 'sensors.reset_distance(port)', opcode: 'RESET_DISTANCE' },
    params: [{ ...PORT }],
    blockPreview: { blockType: 'sensor_reset_distance', fields: { PORT: 'G1' } },
    seeAlso: ['sensors/distance'],
  },
  {
    slug: 'sensors/reset-heading',
    title: 'sensors.reset_heading',
    category: 'Sensors & Data',
    summary: 'Mengembalikan arah hadap ke nol.',
    description: 'Menyetel ulang sudut arah hadap ke 0 derajat.',
    signature: { python: 'sensors.reset_heading(port)', opcode: 'RESET_HEADING' },
    params: [{ ...PORT }],
    blockPreview: { blockType: 'sensor_reset_heading', fields: { PORT: 'G1' } },
    seeAlso: ['sensors/heading'],
  },
];
