// scripts/postbuild.mjs
//
// Runs after `next build`. Emits into out/:
//   - .htaccess    : HTTPS force, SPA 404, immutable caching, compression, MIME,
//                    security + Permissions-Policy (camera/bluetooth) for the AI/BLE stack.
//   - version.json : { sha, builtAt } so Settings can answer "versi berapa?".
//   - sitemap.xml  : derived from the routes actually exported into out/ (not a
//                    hardcoded list, which would rot the moment a page is added).
// Never fails the build for a missing out/ (e.g. dev) — it just no-ops.

import { execSync } from 'node:child_process';
import { writeFileSync, existsSync, readdirSync } from 'node:fs';
import { join, sep } from 'node:path';

const SITE_URL = 'https://hub.robotku.id';

const OUT = join(process.cwd(), 'out');
if (!existsSync(OUT)) {
  console.warn('[postbuild] out/ not found — skipping (did you run `next build`?).');
  process.exit(0);
}

// --- version.json ---------------------------------------------------------
function gitSha() {
  try {
    return execSync('git rev-parse --short HEAD', { stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim();
  } catch {
    return 'unknown';
  }
}
const version = {
  sha: process.env.GITHUB_SHA?.slice(0, 7) || gitSha(),
  builtAt: new Date().toISOString(),
};
writeFileSync(join(OUT, 'version.json'), JSON.stringify(version, null, 2));

// --- .htaccess ------------------------------------------------------------
// HSTS is opt-in: a wrong Strict-Transport-Security header locks the site out of
// browsers for max-age and can't be undone quickly. Only enable it via
// ENABLE_HSTS=1 once HTTPS is verified working in production.
const hstsHeader =
  process.env.ENABLE_HSTS === '1'
    ? '\n  Header set Strict-Transport-Security "max-age=31536000; includeSubDomains"'
    : '';

// The HTTPS redirect is OPT-IN. On a shared host with no panel access, an
// unconditional redirect written BEFORE the TLS cert exists sends every visitor
// to a certificate-error page with no way to undo it except re-uploading. So it
// is only written when ENABLE_HTTPS_REDIRECT=1 — turn it on ONLY after
// `curl -sSI https://hub.robotku.id` answers without a TLS error. Web Bluetooth /
// Web Serial still need HTTPS, so enable it as soon as the cert is confirmed.
const httpsRedirectOn = process.env.ENABLE_HTTPS_REDIRECT === '1';
const httpsRedirectBlock = httpsRedirectOn
  ? `
# --- Force HTTPS (Web Bluetooth / Web Serial / getUserMedia need a secure context) ---
RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
`
  : `
# --- HTTPS redirect DISABLED (set ENABLE_HTTPS_REDIRECT=1 once the TLS cert is live) ---
`;

const htaccess = `# Generated by scripts/postbuild.mjs — do not edit by hand.

# --- Directory listing off (no auto-index of folders without an index.html) ---
Options -Indexes
${httpsRedirectBlock}
# --- 404 fallback (Next exports 404/index.html with trailingSlash) ---
ErrorDocument 404 /404/index.html

# --- Compression ---
<IfModule mod_deflate.c>
  AddOutputFilterByType DEFLATE text/html text/css application/javascript application/json image/svg+xml
</IfModule>
<IfModule mod_brotli.c>
  AddOutputFilterByType BROTLI_COMPRESS text/html text/css application/javascript application/json image/svg+xml
</IfModule>

# --- Caching ---
# Only /_next/ files are content-hashed (a change is a NEW filename), so only they
# are safe to freeze as immutable. Stable-named assets (sim3d/, brand/, og-image,
# favicon) get a short TTL + stale-while-revalidate — otherwise a bad or updated
# upload gets pinned at the CDN for a year and re-uploading the origin does nothing.
<IfModule mod_headers.c>
  <If "%{REQUEST_URI} =~ m#^/_next/#">
    Header set Cache-Control "public, max-age=31536000, immutable"
  </If>
  <ElseIf "%{REQUEST_URI} =~ m#\\.(js|css|woff2|webp|png|jpe?g|glb|hdr|wasm|ico)$#">
    Header set Cache-Control "public, max-age=86400, stale-while-revalidate=604800"
  </ElseIf>
  <FilesMatch "\\.html$">
    Header set Cache-Control "no-cache"
  </FilesMatch>
  Header set Cache-Control "no-cache" "expr=%{REQUEST_URI} =~ m#/version\\.json$#"

  # --- Security headers ---
  Header set X-Content-Type-Options "nosniff"
  Header set Referrer-Policy "strict-origin-when-cross-origin"
  # Explicitly allow camera + bluetooth + serial — a restrictive default silently
  # kills the AI camera panel (camera) and Web Serial / Web Bluetooth robot links.
  # serial=(self) is written explicitly so a later "tidy-up" can't drop it unnoticed.
  Header set Permissions-Policy "camera=(self), microphone=(), geolocation=(), bluetooth=(self), serial=(self)"${hstsHeader}
</IfModule>

# --- MIME types (MediaPipe/tfjs .wasm, 3D .glb/.hdr, .webp) ---
<IfModule mod_mime.c>
  AddType application/wasm .wasm
  AddType model/gltf-binary .glb
  AddType image/vnd.radiance .hdr
  AddType image/webp .webp
</IfModule>
`;
writeFileSync(join(OUT, '.htaccess'), htaccess);

// --- sitemap.xml ----------------------------------------------------------
// Every route Next exported is an `index.html` somewhere under out/. Walk them,
// turn each dir into a canonical trailing-slash URL, and skip error pages.
function routesFromExport(root) {
  const routes = [];
  for (const entry of readdirSync(root, { recursive: true, withFileTypes: true })) {
    if (entry.name !== 'index.html') continue;
    const dir = entry.parentPath ?? entry.path; // parentPath (Node 20.12+), path (older)
    const rel = dir.slice(root.length).split(sep).filter(Boolean).join('/');
    const route = rel ? `/${rel}/` : '/';
    if (/^\/(404|500)\//.test(route)) continue;
    if (route.includes('[')) continue; // dynamic-route placeholder (e.g. /lessons/[id]/), not a real URL
    routes.push(route);
  }
  return [...new Set(routes)].sort();
}

const lastmod = version.builtAt.slice(0, 10); // YYYY-MM-DD
const urls = routesFromExport(OUT)
  .map((r) => `  <url>\n    <loc>${SITE_URL}${r}</loc>\n    <lastmod>${lastmod}</lastmod>\n  </url>`)
  .join('\n');
const sitemap = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`;
writeFileSync(join(OUT, 'sitemap.xml'), sitemap);

console.log(
  `[postbuild] wrote out/.htaccess, out/version.json (sha ${version.sha}), out/sitemap.xml.`,
);
console.log(
  `[postbuild] HTTPS redirect: ${httpsRedirectOn ? 'ON' : 'OFF'}  |  HSTS: ${
    process.env.ENABLE_HSTS === '1' ? 'ON' : 'OFF'
  }`,
);
