// scripts/postbuild.mjs
//
// Runs after `next build`. Emits into out/:
//   - .htaccess    : HTTPS force, SPA 404, immutable caching, compression, MIME,
//                    security + Permissions-Policy (camera/bluetooth) for the AI/BLE stack.
//   - version.json : { sha, builtAt } so Settings can answer "versi berapa?".
// Never fails the build for a missing out/ (e.g. dev) — it just no-ops.

import { execSync } from 'node:child_process';
import { writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const OUT = join(process.cwd(), 'out');
if (!existsSync(OUT)) {
  console.warn('[postbuild] out/ not found — skipping (did you run `next build`?).');
  process.exit(0);
}

// --- version.json ---------------------------------------------------------
function gitSha() {
  try {
    return execSync('git rev-parse --short HEAD', { stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim();
  } catch {
    return 'unknown';
  }
}
const version = { sha: process.env.GITHUB_SHA?.slice(0, 7) || gitSha(), builtAt: new Date().toISOString() };
writeFileSync(join(OUT, 'version.json'), JSON.stringify(version, null, 2));

// --- .htaccess ------------------------------------------------------------
const htaccess = `# Generated by scripts/postbuild.mjs — do not edit by hand.

# --- Force HTTPS (Web Bluetooth / Web Serial / getUserMedia need a secure context) ---
RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

# --- 404 fallback (Next exports 404/index.html with trailingSlash) ---
ErrorDocument 404 /404/index.html

# --- Compression ---
<IfModule mod_deflate.c>
  AddOutputFilterByType DEFLATE text/html text/css application/javascript application/json image/svg+xml
</IfModule>
<IfModule mod_brotli.c>
  AddOutputFilterByType BROTLI_COMPRESS text/html text/css application/javascript application/json image/svg+xml
</IfModule>

# --- Caching: hashed static assets are immutable for a year; HTML must revalidate ---
<IfModule mod_headers.c>
  <FilesMatch "\\.(js|css|woff2|webp|png|jpg|glb|hdr|wasm)$">
    Header set Cache-Control "public, max-age=31536000, immutable"
  </FilesMatch>
  <FilesMatch "\\.html$">
    Header set Cache-Control "no-cache"
  </FilesMatch>
  Header set Cache-Control "no-cache" "expr=%{REQUEST_URI} =~ m#/version\\.json$#"

  # --- Security headers ---
  Header set X-Content-Type-Options "nosniff"
  Header set Referrer-Policy "strict-origin-when-cross-origin"
  # Explicitly allow camera + bluetooth — a restrictive default silently kills the AI panel.
  Header set Permissions-Policy "camera=(self), microphone=(), geolocation=(), bluetooth=(self)"
</IfModule>

# --- MIME types (MediaPipe/tfjs .wasm, 3D .glb/.hdr, .webp) ---
<IfModule mod_mime.c>
  AddType application/wasm .wasm
  AddType model/gltf-binary .glb
  AddType image/vnd.radiance .hdr
  AddType image/webp .webp
</IfModule>
`;
writeFileSync(join(OUT, '.htaccess'), htaccess);

console.log(`[postbuild] wrote out/.htaccess and out/version.json (sha ${version.sha}).`);
